plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'kotlin-parcelize'
    id 'kotlin-kapt'
}

android {

    signingConfigs {
        release {
            storeFile file('/home/chaolee/AndroidStudioProjects/keystore/new_key.jks')
            storePassword '86637971'
            keyAlias = 'chaolee1959'
            keyPassword '86637971'
        }
    }

    compileSdk sdk_version.compile

    defaultConfig {

        targetSdk sdk_version.target
        minSdk sdk_version.min

        applicationId = "com.smile.karaokeplayer"
        manifestPlaceholders["flavorLegacyExternalStorage"] = "true"
        manifestPlaceholders["google_AdMobAppID"] = "ca-app-pub-8354869049759576~5549171584"

        multiDexEnabled true
        versionCode 895
        versionName "8.95"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        signingConfig signingConfigs.release
    }

    flavorDimensions += ["karaoke"]
    productFlavors {
        create("karaokePlayer") {
            dimension = "karaoke"
            applicationId = "com.smile.karaokeplayer"
        }
        create("karaokeTvPlayer") {
            dimension = "karaoke"
            versionCode 100
            versionName "1.00"
            applicationId = "com.smile.karaoketvplayer"
        }
    }

    sourceSets {
        main {
            java.srcDir("src/main/java")
            resources.srcDir("src/main/rec")
            manifest {
                srcFile "src/main/AndroidManifest.xml"
            }
        }
        karaokePlayer {
            java {
                srcDirs += "src/karaokeplayer/java"
                // exclude "**/ExoPlaybackPreparer.java"
            }
            res.srcDirs += "src/karaokeplayer/res"
            manifest {
                srcFile "src/karaokeplayer/AndroidManifest.xml"
            }
        }

        karaokeTvPlayer {
            java.srcDirs += "src/karaoketvplayer/java"
            res.srcDirs += "src/karaoketvplayer/res"
            manifest {
                srcFile "src/karaoketvplayer/AndroidManifest.xml"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    /*
    kotlinOptions {
        jvmTarget = '17'    // deprecated
        // for default fun of Kotlin
        freeCompilerArgs = ['-Xjvm-default=all']    // deprecated
    }
    */

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.15'
    }

    buildFeatures  {
        dataBinding true    // viewBinding true
        buildConfig true
        compose true
    }

    namespace 'com.smile.karaoke'
    // testNamespace 'com.smile.karaoke.androidTest'
}

allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.media:media:1.7.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "androidx.annotation:annotation:1.9.1"
    implementation 'com.facebook.android:audience-network-sdk:6.20.0'
    implementation 'com.facebook.infer.annotation:infer-annotation:0.18.0'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-ads:23.6.0'

    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'

    // Compose BOM (Bill of Materials) - Recommended for managing versions
    // Use the latest BOM version
    implementation platform('androidx.compose:compose-bom:2025.07.00')
    // Compose Runtime
    implementation 'androidx.compose.runtime:runtime'
    // Other Compose dependencies you might be using (UI, Material, etc.)
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.material3:material3' // Or material
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.activity:activity-ktx:1.10.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.2'
    implementation 'androidx.activity:activity-compose:1.10.1'
    implementation 'androidx.compose.ui:ui-graphics'

    implementation 'androidx.media3:media3-exoplayer:1.7.1'
    implementation 'androidx.media3:media3-exoplayer-dash:1.7.1'
    implementation 'androidx.media3:media3-decoder:1.7.1'

    implementation 'androidx.media3:media3-ui:1.7.1'
    implementation 'androidx.media3:media3-session:1.7.1'
    implementation 'androidx.media3:media3-cast:1.7.1'
    implementation 'androidx.mediarouter:mediarouter:1.8.1'
    // implementation 'com.google.android.gms:play-services-cast-framework:22.1.0'

    implementation "com.android.billingclient:billing-ktx:8.0.0"

    /*
    implementation("io.ktor:ktor-server-core-jvm:3.2.0") // Or latest version
    implementation("io.ktor:ktor-server-cio-jvm:3.2.0")  // CIO engine for Ktor
    implementation("io.ktor:ktor-server-content-negotiation-jvm:3.2.0") // For content negotiation if needed
    implementation("io.ktor:ktor-serialization-kotlinx-json-jvm:3.2.0") // If you need JSON
    */

    implementation 'androidx.tracing:tracing-perfetto-handshake:1.0.0'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'

    implementation files('libs/smilelibraries-release.aar')
    implementation files('libs/NativeTemplatesModels-release.aar')

    implementation project(':extension-ffmpeg')
    implementation project(':extension-flac')
    implementation project(':extension-opus')
    implementation project(':extension-vp9')
    implementation project(':extension-av1')

    implementation 'org.videolan.android:libvlc-all:4.0.0-eap1'

    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation platform('androidx.compose:compose-bom:2025.07.00')
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.ext:truth:1.6.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}

// apply plugin: 'com.google.gms.google-services'
if (!gradle.startParameter.taskRequests.toString().toLowerCase()
        .contains("karaoketvplayer")) {
    apply plugin: 'com.google.gms.google-services'
}
