
apply plugin: 'com.android.library'

android {
    compileSdk sdk_version.compile

    defaultConfig {
        targetSdk sdk_version.target
        minSdk sdk_version.min
        consumerProguardFiles 'proguard-rules.txt'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    sourceSets.main {
        jniLibs.srcDir 'src/main/libs'
        jni.srcDirs = [] // Disable the automatic ndk-build call by Android Studio.
    }

    namespace 'androidx.media3.decoder.vp9'
}

dependencies {
    implementation "androidx.annotation:annotation:1.9.1"
    implementation 'androidx.media3:media3-common:1.8.0'
    implementation 'androidx.media3:media3-exoplayer:1.8.0'
    implementation 'androidx.media3:media3-decoder:1.8.0'
    compileOnly 'org.checkerframework:checker-qual:3.49.5'
    compileOnly 'org.jetbrains.kotlin:kotlin-annotations-jvm:1.9.22'
}
