
apply plugin: 'com.android.library'

android {
    compileSdk sdk_version.compile

    defaultConfig {
        targetSdk sdk_version.target
        minSdk sdk_version.min
        consumerProguardFiles 'proguard-rules.txt'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        ndk {
            abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
        }
        externalNativeBuild {
            cmake {
                // Debug CMake build type causes video frames to drop,
                // so native library should always use Release build type.
                arguments "-DCMAKE_BUILD_TYPE=Release"
                arguments "-DBUILD_TESTING=OFF"
                targets "gav1JNI"
            }
        }
    }

    // ndkVersion '22.1.7171670'
    ndkVersion '26.3.11579264'
    // or
    // ndkPath "home/chaolee/Android/Sdk/ndk/21.4.7075529"  // Point to your own NDK
    externalNativeBuild {
        cmake {
            path file('../av1/src/main/jni/CMakeLists.txt')
            version '3.21.0+'
        }
    }

    sourceSets.main {
        // As native JNI library build is invoked from gradle, this is
        // not needed. However, it exposes the built library and keeps
        // consistency with the other extensions.
        jniLibs.srcDir 'src/main/libs'
        // jni.srcDirs = [] // Disable the automatic ndk-build call by Android Studio.
    }

    namespace 'androidx.media3.decoder.av1'
}

dependencies {
    implementation "androidx.annotation:annotation:1.9.1"
    implementation 'androidx.media3:media3-common:1.8.0'
    implementation 'androidx.media3:media3-exoplayer:1.8.0'
    implementation 'androidx.media3:media3-decoder:1.8.0'
    compileOnly 'org.checkerframework:checker-qual:3.49.5'
    compileOnly 'org.jetbrains.kotlin:kotlin-annotations-jvm:1.9.22'
}
